# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://test.akceleracje.uw.edu.pl" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Chóralne Akceleracje
  avatar:
  gravatar: # Email MD5 hash
  description: "Coroczne wiosenne spotkanie chórów wydziałowych Uniwersytetu Warszawskiego" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Chóralne Akceleracje</h1>
     <p>Coroczne wiosenne spotkanie chórów wydziałowych Uniwersytetu Warszawskiego</p>
  header_text_feature_image: img/photos/8/IMG_5324.jpg
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "Ch%C3%B3ralne-Akceleracje-1423393037901702/"
  flickr:
  github:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Śledź nas na"
  str_rss_follow: "Śledź RSS"
  str_email: "Email"
  str_next: "Następne"
  str_prev: "Poprzednie"
  str_continue_reading: "Czytaj dalej"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
